[#section-terms]
[glossary]
== Список терминов

non-real-time systems:: системы общего назначения
round-robin:: круговое обслуживание
static time scheduling algorithm:: статическое планирование
rate-monotonic scheduling:: монотонное планирование скорости
tick hook functions:: функции перехвата, вызванные прерыванием тика
idle hook functions:: функции перехвата, вызванные задачей ожидания
Full interrupt nesting model:: модель полной вложенности прерываний
Third party contributions:: сторонние контрибуции
core of the kernel:: ядро ядра
best-fit:: алгоритм наибольшего соответствия
deeply embedded:: глубоко встраиваемые
task prior state:: предшествующее состояние задачи
ready (task state):: готова к выполнению
running (task state):: выполняется
blocked (task state):: заблокирована
suspended (task state):: приостановлена
resume operation:: операция возобновления
run tasks of equal priority in a time slice manner:: выполнение задач с одинаковым приоритетом в режиме «нарезания времени»
fixed-function accelerators:: ускорители с фиксированными функциями
tool flow:: поток инструментов
coroutines:: сопрограммы/корутины
ISA (Instruction Set Architecture):: архитектура набора команд