ifdef::env-github[]
:imagesdir: ../images
:riscv: RISC&#8209;V
:tip-caption: :bulb:
:note-caption: :memo:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Методы отладки

Отладка -- неотъемлемая часть жизненного цикла разработки программного обеспечения.
Даже при самых надежных методах программирования возникают ошибки, и их отладка -- не самое приятное занятие.
В любом широко используемом программном обеспечении над кодом работают многие разработчики, и отладка занимает значительную часть их времени.
Именно поэтому такие методологии разработки программного обеспечения, как
https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_%D1%87%D0%B5%D1%80%D0%B5%D0%B7_%D1%82%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5[TDD]
(Test Driven Development, разработка через тестирование),
https://en.wikipedia.org/wiki/Defensive_programming[защитное программирование] и
https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%BD%D1%82%D1%80%D0%B0%D0%BA%D1%82%D0%BD%D0%BE%D0%B5_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5[контрактное программирование], приняты многими организациями.
Некоторые языки программирования даже обеспечивают поддержку некоторых методологий;
например, https://ru.wikipedia.org/wiki/D_(%D1%8F%D0%B7%D1%8B%D0%BA_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)[D]
реализует функции https://dlang.org/spec/contracts.html[контрактного программирования].

Отладка нативных приложений затруднена из-за семантики языка программирования, разнообразия зависимого программного обеспечения,
зависимости от аппаратных характеристик, таких как модель потоков, модель памяти и т. д.
Поэтому очень важно знать различные технологии отладки, доступные нам.
В этой главе мы представим различные инструменты отладки и дадим краткое введение в каждый из них.

Сначала мы познакомимся с различными типами ошибок, которые встречаются в программном обеспечении, а затем изучим различные инструменты, облегчающие процесс отладки.

После знакомства с этой главой вы будете уметь:

* предотвращать появление многих ошибок с помощью защитных методов;
* использовать инструменты для своевременного обнаружения ошибок, позволяющие сэкономить много времени;
* использовать правильные инструменты и методы для отладки.

=== Типы ошибок в программах

В целом, сбои в работе приложений можно разделить на три категории:

[arabic]
. Ошибки программирования (синтаксические ошибки, семантические ошибки, ошибки времени выполнения).
. Сбой системы (ошибки памяти, повреждение файла, сбой сети и т.д.).
. Недействительные данные (некорректное имя файла, некорректные данные).

Некоторые ошибки трудно отнести к определенному классу, поскольку классификация может зависеть от точки отсчета.
Например, повреждение данных в одном приложении может привести к тому, что зависимое приложение выдаст ошибку времени выполнения.
В зависимости от типа сбоя применяются различные инструменты и методологии.
В этой главе мы сосредоточимся на ошибках программирования, а в следующих разделах представим инструменты и методики, относящиеся к ним.

=== Инструменты и методы отладки

При работе с тулчейном, настройке системы или разработке системного программного обеспечения часто используемые методы отладки можно разделить на четыре категории:

[arabic]
. Отладка на основе инструментирования
. Использование отладчика
. Удалённая отладка с помощью `gdb`
. Отладка на основе JTAG

==== Отладка на основе инструментирования

Методы отладки на основе инструментирования -- это методы вставки кода в программы вручную или программно.
Это помогает получить представление о коде во время выполнения программы.
Есть три наиболее широко используемых подхода:

:assetion: footnote:[Примечание переводчика: дословно термин означает «утверждение», но для ясности изложения этот вариант в тексте не используется.]

[arabic]
. Отладочная печать
. Отладка на основе `assertion`’ов
. Использование санитайзеров

Если отладочная печать и отладка на основе `assertion`’ов -- одни из самых ранних методов отладки, то санитайзеры появились относительно недавно.
Ниже мы кратко опишем каждую технику.

===== Отладочная печать

Простейшая техника отладки заключается в добавлении в программу набора операторов печати и наблюдении за выводимыми значениями.
Вставка операторов печати в тщательно определенные точки программы может помочь отладить программу.
Это один из самых ранних методов отладки, и он весьма полезен даже сегодня.
Однако в ряде случаев этот подход не срабатывает, поскольку он плохо масштабируется.
Если программист не обладает хорошим знанием кода, то при таком подходе трудно быстро найти проблемы.

===== Отладка на основе `assertion`

Чтобы установить пред- и постусловия в различных точках программы, обычно вставляются `assertion`’ы.
Ошибка в `assertion` упрощает отладку.
Это также помогает обнаруживать ошибки на ранней стадии разработки.
Обычно `assertion` отключены в производственном коде, поэтому одним из первых шагов по отладке является включение `assertion` и запуск неудачного тестового сценария.

===== Санитайзеры

И clang, и GCC предоставляют инструментарий (санитайзеры), который может обнаружить несколько известных классов ошибок, таких как переполнение
буфера, повреждение памяти и многих других. Существуют санитайзеры адресов, памяти, неопределенного поведения, потоков и прочие.
Это обеспечивает автоматизированный способ обнаружения ошибок.
Санитайзеры также требуют поддержки времени выполнения для поиска ошибок, а она доступна не на всех платформах.
Например, {riscv} в настоящее время поддерживает только санитайзер адресов и санитайзер потоков.
https://github.com/google/sanitizers[Этот документ] является источником достоверной информации для всей документации по санитайзерам.

На некоторых платформах https://valgrind.org/[Valgrind] также может обнаружить ошибки,
которые выявляются некоторыми санитайзерами, например, повреждение памяти или её утечки.
К сожалению, в настоящее время Valgrind недоступен для платформ {riscv}.

==== Нативная отладка с помощью отладчика

:backtrace: footnote:[Примечание переводчика: исторически в gdb используется термин backtrace для обозначения трассировки стека (stack trace), поэтому команда и называется bt.]

Когда есть отладчик, становится очень удобно проверять программы, получать трассировку стека, значения объектов, состояние различных потоков и т.д.
Обучение эффективному использованию отладчика, такого как `gdb`, значительно упрощает разработку программного обеспечения.
Часто используемыми командами `gdb` являются:

* `gdb --args <binary> <args>` для запуска программы со списком аргументов.
* `b FileName:linenum` для установки точек останова
* `bt` для получения трассировки стека{backtrace}
* `thread apply all bt` для получения трассировки стека для всех потоков
* `p variableName` для печати значения переменной/объекта
* `up` для перехода вверх по кадру стека
* `down` для перехода вниз по кадру стека
* `l` для перечисления исходных строк кода вокруг текущего фрейма стека
* `disassemble` для отображения ассемблерного кода текущей функции
* `n` для выполнения следующей инструкции источника
* `si` для выполнения следующей машинной инструкции
* `q` для выхода из отладчика
* `r` для запуска программы

В сети существует множество источников, которые помогут вам начать работу с `gdb`, но вышеупомянутого списка команд достаточно для обычной повседневной отладки.
Документацию по `gdb` можно найти в https://www.gnu.org/software/gdb/documentation/[здесь].

==== Удалённая отладка

`gdb` можно использовать для отладки программ, запущенных на другой машине.
На удаленной машине запускается программа `gdbserver`, которая отвечает на запросы `gdb` клиентской машины.
В некоторых случаях удаленная отладка может быть более удобной;
например, она позволяет проверить программу на машине, где произошла ошибка, вместо того,
чтобы пытаться повторить сценарий на компьютере разработчика. Это может сэкономить много времени.
Удаленная отладка довольно популярна среди разработчиков мобильных приложений,
когда приложение запускается на мобильном устройстве, а отладчик -- на машине разработчика.

В случае заинтересованности вы можете начать работу со
https://developers.redhat.com/blog/2015/04/28/remote-debugging-with-gdb[статьи блога «Удаленная отладка с GDB»].
Страница https://man7.org/linux/man-pages/man1/gdbserver.1.html[руководства gdbserver(1) -- Linux] также предлагает отличную документацию.
В официальном https://github.com/riscvarchive/riscv-binutils-gdb[репозитории {riscv} binutils] есть исходный код `gdbserver`.

==== Отладка на основе JTAG

На ранней стадии ввода в эксплуатацию аппаратного обеспечения отсутствуют программные возможности.
Для отладки «голых» приложений или доступа к различным аппаратным блокам в качестве транспортного механизма
используется JTAG (названный в честь Joint Test Action Group).
Большинство современных аппаратных средств предоставляют возможность прямой трассировки инструкций и данных
с помощью стандартного протокола JTAG, хотя у каждого производителя аппаратных средств может быть разный уровень поддержки.
Он часто используется для отладки аппаратных неполадок.
{riscv} определяет стандартный интерфейс для внешней отладки, который включает в себя
доступ к аппаратным потокам (hart) с самой первой инструкции, доступ к памяти, пошаговые инструкции и т. д.

=== Справочные материалы

* https://www.cs.cornell.edu/courses/cs312/2006fa/lectures/lec26.html[Корнельский университет, CS312 Лекция 26, Техники отладки]
* https://www.sourceware.org/gdb/current/onlinedocs/gdb.html[Отладка с помощью GDB]
* https://riscv.org/wp-content/uploads/2016/01/Tues1030-{riscv}-External-Debug.pdf[Тим Ньюсом -- Внешняя отладка {riscv} (она же JTAG-отладка)]
* https://riscv.org/wp-content/uploads/2019/03/riscv-debug-release.pdf[Тим Ньюсом и Меган Вакс -- Поддержка внешней отладки {riscv} в версии 0.13.2]
* https://five-embeddev.com/riscv-debug-spec/latest/introduction.html#sec:intro[Five EmbedDev -- Блог о встраиваемой {riscv}]
* https://www.cs.usfca.edu/~parrt/course/601/lectures/programming.by.contract.html[Университет Сан-Франциско -- Программирование «по контракту»]
* https://github.com/riscv/riscv-isa-sim#debugging-with-gdb[Отладка с помощью Gdb]
* https://youtu.be/q2zztv9Z9i4[Константин Владимиров -- Специальный выпуск: лекции по тулчейну, часть 4, линкеры и отладка]
