ifdef::env-github[]
:imagesdir: ../images
:riscv: RISC&#8209;V
:tip-caption: :bulb:
:note-caption: :memo:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Создание приложений {riscv}

В этой главе мы узнаем, как использовать популярные системы компиляции (как LLVM, так и GCC) для создания приложений {riscv},
а также как запускать приложения на симуляторах и эмуляторах.
В этой главе представлены вводные материалы, которые помогут вам получить практический опыт создания и запуска приложений {riscv}.
Поскольку инструменты и их зависимости часто меняются, некоторые аспекты этого курса могут работать некорректно до тех пор,
пока не будет произведено обновление курса.
Помня об этом, мы приводим ссылки на официальные списки рассылки, репозитории GitHub и веб-сайты.
Они могут оказаться весьма полезными, если вы захотите углубиться в какие-либо области разработки {riscv}.

В этой главе мы обсудим:

* введение в тулчейн {riscv};
* где скачать тулчейны и симулятор;
* создание приложений с помощью этих тулчейнов;
* запуск приложений на симуляторе;
* запуск приложений на эмуляторе;
* полезные справочные материалы.

=== Введение в системы компиляции {riscv}

Есть две наиболее популярных системы компиляции {riscv}.

[arabic]
. GNU {riscv}
. LLVM {riscv}

Обе системы предоставляют оптимизирующий компилятор, ассемблер, компоновщик и другие различные инструменты для создания
приложений, работающих на машинах {riscv}.
Официальный https://github.com/riscv-collab/riscv-gcc[репозиторий {riscv} на GitHub] предоставляет исходный код для тулчейна `riscv-gnu`,
тулчейн в собранном виде можно скачать по https://github.com/riscv-collab/riscv-gnu-toolchain[ссылке]
Компилятор {riscv} обычно используется в качестве кросс-компилятора,
поскольку многие процессоры {riscv} используются для встраиваемых приложений с низким энергопотреблением.
В настоящее время кросс-компиляторы {riscv} можно запускать только на
https://en.wikipedia.org/wiki/Comparison_of_executable_file_formats[целевых платформах ELF] таких, как Linux-машины.

Тулчейн {riscv} LLVM недоступен у сторонних поставщиков, но его можно собрать из исходников, загрузив проект
https://github.com/llvm/llvm-project[llvm-project] с открытым кодом.
Позже будет описан простой способ использования тулчейна llvm с gnu sysroot.

Симулятор {riscv} можно загрузить из официального репозитория {riscv} на GitHub:
https://github.com/riscv-software-src/riscv-isa-sim[riscv/riscv-isa-sim:Spike, симулятор {riscv} ISA].
Хотя платы {riscv} легко доступны у нескольких производителей, разработку {riscv} проще начать, используя симуляторы.

=== Создание приложений с помощью тулчейна

Для создания приложения для {riscv} использование инструментальной цепочки кросс-компилятора не отличается от любой другой системы разработки на основе кросс-компилятора.
Требуется две вещи:

* система компиляции
* sysroot

В <<section-chapter1>> мы описали систему компиляции и `sysroot`.
Прежде чем научиться создавать приложения с помощью тулчейна {riscv},
мы хотели бы представить интересное соглашение об именовании, которое используется для кросс-компиляторов.

==== Соглашение об именовании компиляторов

Загрузив тулчейн GCC, в каталоге `bin` вы найдете двоичный файл `riscv64-unknown-elf-gcc`.
Это тот же самый компилятор GCC со встроенной информацией о `sysroot` и платформе.
Это соглашение -- называть кросс-компиляторы таким образом. Обычно для именования используется формат `arch-vendor-os-abi`.
Так, `riscv64-unknown-elf-gcc` означает, что это кросс-компилятор для {riscv} 64 bit,
и он будет генерировать двоичный файл `elf`, который может работать, например, на машинах Linux.
Отличный справочник по соглашениям об именовании можно найти
http://web.eecs.umich.edu/~prabal/teaching/eecs373-f12/notes/notes-toolchain.pdf[здесь].
В случаях, когда имя компилятора не содержит целевого триплета, для его получения можно использовать флаг `-dumpmachine`:

[source,bash]
----
gcc -dumpmachine
# x86_64-linux-gnu
----

Имея под рукой компилятор `riscv64-unknown-elf-gcc`, файл можно скомпилировать следующими способами:

[source,bash]
----
riscv64-unknown-elf-gcc -O2 -o a.out hello.c
----

[source,bash]
----
riscv64-unknown-elf-gcc -O2 hello.c -mabi=lp64d -march=rv64ifd
----
:mabi: footnote:[Примечание переводчика: не просто модель даннных, а двоичный интерфейс приложения (ABI).]

Флаг `-march` используется для указания целевой субархитектуры, для которой будет сгенерирована сборка.
Флаг `-mabi` используется для указания моделей данных{mabi}.
Более подробную информацию о моделях данных можно найти в
https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models[этом разделе] Википедии о 64-битовых вычислениях.

С помощью тулчейна llvm двоичный файл может быть собран аналогичным образом.
Предполагается, что `sysroot` находится в каталоге `riscv64-unknown-elf`:

[source,bash]
----
clang test.c -c --sysroot riscv64-unknown-elf -target
# riscv64-unknown-elf -march=rv64ifd
----

Приложения {riscv} можно запускать как на устройствах, так и на симуляторах или эмуляторах.
Мы кратко обсудим, как запустить приложение на симуляторе, а также на эмуляторе.

=== Запуск приложений на симуляторе Spike

Одним из самых удобных способов запуска небольших приложений является использование симулятора {riscv}.
Шаги по сборке и установке достаточно просты.
Для этого вам понадобятся следующие зависимости:

[arabic]
. Linux-машина -- создание образа Linux на других машинах нетривиально, поэтому для начала рекомендуется использовать Linux-машину.
. Тулчейн {riscv}: https://github.com/riscv-software-src
. Spike, симулятор
{riscv}: https://github.com/riscv-software-src/riscv-isa-sim
. pk, прокси-ядро {riscv}: https://github.com/riscv-software-src/riscv-pk

Инструкции по запуску простого приложения `hello-world` на симуляторе Spike приведены в
https://github.com/riscv-software-src/riscv-isa-sim#compiling-and-running-a-simple-c-program[README] репозитория симулятора.
Чтобы установить прокси-ядро, следуйте инструкциям в https://github.com/riscv-software-src/riscv-pk#build-steps[README] репозитория `pk`.
Для удобства вы можете установить и `spike`, и `pk` в тот же каталог, что и каталог тулчейна `riscv64`, указав путь к нему в качестве префикса установки для обоих.

=== Запуск приложений на эмуляторе

Запуск приложения {riscv} на эмуляторе обеспечивает большую гибкость, чем на симуляторе, но этапы установки требуют больше усилий.
Чтобы запустить приложение {riscv} на эмуляторе, необходимо иметь следующие зависимости:

[arabic]
. Linux-машина -- создание образа Linux на других машинах нетривиально,
поэтому для начала рекомендуется использовать Linux-машину.
. тулчейн
{riscv}: https://github.com/riscv-software-src
. QEMU: `+git clone --depth 1 --branch v5.0.0 https://github.com/qemu/qemu+`
. Linux: `+git clone --depth 1 --branch v5.4 https://github.com/torvalds/linux+`
. Busybox: `+git clone --depth 1 git://git.busybox.net/busybox+`

Перечисленные выше ветки репозиториев являются предлагаемыми версиями, которые могут часто меняться.
Вы можете выбрать и другие.
Приведенная выше документация может устареть, если в какой-либо из зависимостей произойдут изменения.
Проверьте страницу документации
https://risc-v-getting-started-guide.readthedocs.io/en/latest/linux-qemu.html[Запуск 64- и 32-битных {riscv} Linux на QEMU], чтобы узнать последние поддерживаемые версии.
Если эта документация не работает, обязательно спросите в списке рассылки http://lists.infradead.org/pipermail/linux-riscv/[linux-riscv].

==== Сборка QEMU для {riscv}

[source,bash]
----
cd qemu
./configure --target-list=riscv64-softmmu --prefix=/path/to/keep/qemu
make -j $(nproc)
make install
----

==== Сборка Linux для целевой системы {riscv}

[source,bash]
----
cd linux
make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- defconfig
make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- -j $(nproc)
----

Убедитесь, что префикс кросс-компилятора совпадает с префиксом вашего тулчейна.
В приведенном выше примере компилятор GCC -- `riscv64-unknown-linux-gnu-gcc`,
поэтому флаг `CROSS_COMPILE` --`riscv64-unknown-linux-gnu-`.

==== Сборка busybox

[source,bash]
----
cd busybox
CROSS_COMPILE=riscv64-unknown-linux-gnu- make defconfig
CROSS_COMPILE=riscv64-unknown-linux-gnu- make -j $(nproc)
----

==== Запуск образа Linux в QEMU

[source,bash]
----
sudo /path/to/keep/qemu/bin/qemu-system-riscv64 -nographic -machine
virt \
     -kernel /path/to/linux/image -append "root=/dev/vda ro
console=ttyS0" \
     -drive file=busybox,format=raw,id=hd0 \
     -device virtio-blk-device,drive=hd0
----

==== Запуск приложения на QEMU на «голом железе»

[source,bash]
----
/path/to/keep/qemu/bin/qemu-system-riscv64 -nographic -machine virt
-kernel /path/to/binary -bios none
----

Дополнительные конфигурации QEMU для {riscv} можно найти в
https://wiki.qemu.org/Documentation/Platforms/RISCV[официальной документации].
Помимо симуляторов и эмуляторов, приложения {riscv} можно запускать на виртуальных машинах, а также на имеющихся в продаже платах для разработки.
Дополнительную документацию по отладке проблем с «голым железом» можно найти
https://embeddedinn.xyz/articles/tutorial/Adding-a-custom-peripheral-to-QEMU/[здесь].
Вы можете установить виртуальную машину {riscv}, как описано в документации https://wiki.debian.org/{riscv}[здесь].

=== Справочные материалы

* mailto:tech-toolchain-runtime@lists.riscv.org[Tech: Toolchain & Runtime Subcommittee mailing list]
* https://wiki.osdev.org/GCC_Cross-Compiler[кросс-компилятор GCC]
* https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models[64-битовые модели данных]
* https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models[архив linux-riscv]
* https://risc-v-getting-started-guide.readthedocs.io/en/latest/linux-qemu.html[Running 64- and 32-bit {riscv} Linux on QEMU]
* https://wiki.qemu.org/Documentation/Platforms/RISCV[Qemu: Документация/Платформы/RISCV]
* https://wiki.debian.org/{riscv}[Debian -- {riscv} Wiki]

*Платы {riscv}*

Страница https://riscv.org/exchange/[{riscv} Exchange]
представляет собой коллекцию доступного физического оборудования в экосистеме {riscv}.
Этот список курируется сообществом.

*Ядра {riscv}*

Страница https://riscv.org/exchange/?_sft_exchange_category=core,cores[{riscv} Exchange: Cores & SoCs] представляет собой коллекцию доступных IP-ядер систем на кристалле (СнК) в экосистеме {riscv}.

*Поставщики тулчейнов и другого аппаратного и программного обеспечения:*

* https://github.com/riscv-collab[{riscv} Software Collaboration]
* https://github.com/sifive/freedom-tools/releases[sifive/freedom-tools]
* https://github.com/lowRISC[lowRISC]
* https://github.com/stnolting/riscv-gcc-prebuilt[stnolting/riscv-gcc-prebuilt]
* https://www.sifive.com/software[SiFive/Software]
